### ISSUE TITLE
after scalling, bones seems to be in the right place on blender, but not on Unity

### ISSUE THREAD

**Issue by Naia-love** [triazo/immersive_scaler#10]
So I tried today for the first time your tool, did my usual things in CATS (importing a VRM avatar) and before exporting I used your tool in CATS (v 0.19.1-dev). In the viewport the scalling seems to have went smootly 
![blender](https://user-images.githubusercontent.com/26840567/158028082-d7a8bc9d-3b97-432b-81ec-dc645db0f680.png)

 but so after importing the avatar in Unity, I realised only after a while of thinkering around others things that the bones wasns't "where they should be" 
![unity_scaled](https://user-images.githubusercontent.com/26840567/158028088-26145014-d6ec-4fab-98b1-3a368eb07a4e.png)

while the nonscalled version is good 
![unity_notscaled](https://user-images.githubusercontent.com/26840567/158028099-446cc37e-80b5-4414-ae60-99d1f0b80577.png)

btw using "master" version, not the last release (for new ik support)

**Comment by Naia-love** [comment]
OKAY 
I'm sorry found out how to fix that, I just needed to start pose mode and apply as rest pose after doing the scalling

**Comment by triazo** [comment]
If it needs reapplying the rest pose that's a bug and something I can add in, but if so it shouldn't detach the bones from the armature like that. From the first image it looks like it scaled the armature but not the mesh, but that's not really how scaling in pose mode fails.
