### ISSUE TITLE
Ensure that X-axis mirror is disabled before rescaling armature

### ISSUE THREAD

**Issue by Asovrix** [triazo/immersive_scaler#17]
Having X-axis mirror enabled can cause bones from non-armature bones such as clothes to get moved in a way to force symmetry on X-axis. That makes sense on humanoid armature, but not on clothes, which can be asymmetrical.
Example before scaling on a bow of this kimono, I hid humanoid bones on this view:
![blender_2023-01-31_12-49-44](https://user-images.githubusercontent.com/44006686/215752355-6248676a-49ee-4f02-978c-f339dcbd2858.png)
After scaling when X-Axis Mirror under Tool option is enabled:
![blender_2023-01-31_12-50-28](https://user-images.githubusercontent.com/44006686/215752531-9fc25732-5862-4950-a529-790992b60fb3.png)

**Comment by triazo** [comment]
Hey, thanks for finding a bug!
I'm trying to reproduce this locally but there's still some difference between your setup and mine, if I just have bones on asymmetric clothing pieces like that and scale with X mirror turned on, they stay in the same spot relative to each other, so there's something else going on. Maybe it's rig setup and maybe it's something with a different blender version but either way I want to fix it so it doesn't happen to others.

Would you mind sending a .blend file that this is an issue on and letting me know your blender and immersive scaler versions? Feel free to dm me on discord at triazo#9607.

**Comment by Asovrix** [comment]
Oh yeah, forgot to mention that I am using Blender 3.4.1 with nightly version of CATS.
I just noticed I am using a slightly old version of Immersive Scaler though, downloaded on 8th of January.
Should I try repro it again with newest one?
