### ISSUE TITLE
Goes based off of total height not eye height

### ISSUE THREAD

**Issue by Mage-Enderman** [triazo/immersive_scaler#2]
Hey. for avatars with tall ears or hats etc this resizes them including that in their height which is fine sometimes
but I feel there should be the option to use eye height

**Comment by triazo** [comment]
I have a toggle for this working locally, I'll add it in the next release with some other features.

**Comment by triazo** [comment]
Eye height has been added in the last couple versions and has worked as expected in several cases. Closing for now.
