### ISSUE TITLE
Blender 4.1.0 interrupts "Get current height" or "Rescale Armature" with error

### ISSUE THREAD

**Issue by OrenjiVR** [triazo/immersive_scaler#21]
On Blender 4.1.0:
When getting the current height of the avatar (or any of the ratios, for that matter), it interrupts with this error message:
`bpy.ops.armature.get_avatar_height()
Python: TypeError: expected sequence size 24, got 8
`
(This also happens when "Rescale Armature" is applied)

Current workaround:
Use Blender 4.0.2

**Comment by triazo** [comment]
Looks like it was an api change, fixed in the latest release.
