### ISSUE TITLE
It won't move the model up after scaling

### ISSUE THREAD

**Issue by Mage-Enderman** [triazo/immersive_scaler#7]
I hit scale and the feet are below the ground
I've tried checking and unchecking every combination of "Core Functionality" etc

I've tried using the CATS Dev build too

I'm on Windows 10 Home using Blender 2.93.8

**Comment by NotAKidoS** [comment]
make sure your skeleton and mesh transforms are applied before using the tool

**Comment by triazo** [comment]
I ran into this myself with one of my models so it's definitely a bug.

Essentially there's a get_lowest_point() function that, well, gets the lowest point on the model, by scanning all the vertices and getting the one with the lowest Z value. For some reason, the in the object's data reflected it pre-scaling and not post.

Going to edit mode and back resets the data but takes a little bit longer. It's not an ideal workaround but for now it should at least be correct.

I'll leave this open until I find out where the vertex data actually is and can get it without the slowdown.

**Comment by triazo** [comment]
Last update redid the code for get_lowest_point, closing out.
