### ISSUE TITLE
Shapekey order is ruined after running script.

### ISSUE THREAD

**Issue by NotAKidoS** [triazo/immersive_scaler#9]
The order of shapekeys are completely changed after running the script. This messes with stuff once imported back into Unity.

https://user-images.githubusercontent.com/37721153/154396128-8985a61c-95e5-4e24-8208-2dccf7e62332.mp4

**Comment by triazo** [comment]
Just checked and this happens in cats during the apply as rest pose, since my code just calls directly into cats. I'll take a look once the height stuff is sorted out, but an imscale update can't or shouldn't fix this.

**Comment by triazo** [comment]
Fixed by #16
